apiVersion: v1
kind: Service
metadata:
  name: multi-port-service
  namespace: nginx
spec:
  type: NodePort / loadbalancer
  selector:
    app: nginx
  ports:
    - name: proxy
      port: 8082
      targetport: 80

    - name: application
      port: 8081
      targetPort: 8080